# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ae38cfb020fb9f09c268b2a377ee3496a2f8be476b40f84e9bef17c0955cb83b0142bc395aca12ac657d5ae9daf33aa6b53584ddf96b1f8cba7c4aec110cc73

test:
  secret_key_base: 6b5b7eff4dfcd65fec0efdd90e18ee750a9de9d0fdc3f7fef1395ae97b4679866999dc69d81e6e27a96fac85b104bfa9ffe086825c116bf0647ef42482f69b64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
